// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pklkbcfxfzropaoelvrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbGtiY2Z4Znpyb3Bhb2VsdnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTI5MzYsImV4cCI6MjA2MTMyODkzNn0.sc-nEJHIO1CGVFEGwip_gSRd2LpVSajT7k9AvgobUGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);